# Develop stage databases mysql.
# -----------------------------------------------
version: '3.7'

volumes:
  test_db_data:

services:
  test_db:
    platform: linux/x86_64
    image: mysql:8.0.33
    volumes:
      - test_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    logging:
      driver: none
  test_redis:
    image: redis:6.2.6-alpine
    container_name: test_cache
    restart: always
    ports:
      - 16379:6379
